name: Auto-sync Fork

on:
  schedule:
    - cron: '*/90 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get upstream URL
      id: get-upstream
      run: |
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}")
        
        UPSTREAM_URL=$(echo "$RESPONSE" | jq -r '.parent.clone_url')
        
        if [ "$UPSTREAM_URL" == "null" ]; then
          echo "::error::This repository is not a fork"
          exit 1
        fi
        
        echo "::set-output name=upstream_url::$UPSTREAM_URL"
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Sync with upstream
      run: |
        if ! git remote | grep -q upstream; then
          git remote add upstream ${{ steps.get-upstream.outputs.upstream_url }}
        fi
        
        git fetch upstream
        
        DEFAULT_BRANCH=$(git remote show upstream | grep 'HEAD branch' | cut -d' ' -f5)
        git checkout $DEFAULT_BRANCH || git checkout -b $DEFAULT_BRANCH upstream/$DEFAULT_BRANCH
        
        git merge upstream/$DEFAULT_BRANCH --no-edit || {
          echo "::error::Merge conflict occurred. Please resolve manually."
          exit 1
        }
        
        git push origin $DEFAULT_BRANCH

    - name: Install jq (dependency)
      if: always()
      run: sudo apt-get install -y jq
