name: Sync with sevcator/zapret-ps1

on:
  schedule:
    - cron: '0 */1 * * *'  # Каждый час (GitHub Actions не поддерживает 90 минут)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Setup upstream
      run: |
        if ! git remote | grep -q upstream; then
          git remote add upstream https://github.com/sevcator/zapret-ps1.git
        fi
        git fetch upstream

    - name: Get default branch
      id: default_branch
      run: |
        DEFAULT_BRANCH=$(git remote show upstream | grep 'HEAD branch' | cut -d' ' -f5)
        echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

    - name: Checkout and merge
      run: |
        git checkout ${{ steps.default_branch.outputs.default_branch }} || 
          git checkout -b ${{ steps.default_branch.outputs.default_branch }} upstream/${{ steps.default_branch.outputs.default_branch }}
        git merge upstream/${{ steps.default_branch.outputs.default_branch }} --no-edit
        git push origin ${{ steps.default_branch.outputs.default_branch }}
